app.common.initLazyLoad();
app.common.toggleMobMenu();
app.navigation.init();
app.ctrl.init();
app.catSlider.init();
app.menu.init();
app.tableInfo.init();
app.scrollToTop.init();
app.formElement.state();
